### ISSUE TITLE
Improve README with details of project

### ISSUE THREAD

**Issue by leportella** [okfn-brasil/perfil#12]

**Comment by amadeu01** [comment]
I'm not used to code in python, so i'm sorry if this is a silly question. 
On the readme of the project: 

> Project is currently developed in Python 3.6.1


But, if you use `Python 3`, shouldn't you be using `pip3` as well? to install dependencies.

**Comment by cuducos** [comment]
> But, if you use `Python 3`, shouldn't you be using `pip3` as well?

No necessarily. It depends on your local setup. In my case, for example, it's always `pip`. `pyenv` or _virtualenv_ make sure `pip` (never `pip3`) is installing packages in the right place.

**Comment by cuducos** [comment]
> But, if you use `Python 3`, shouldn't you be using `pip3` as well?

No necessarily. It depends on your local setup. In my case, for example, it's always `pip`. `pyenv` or _virtualenv_ make sure `pip` (never `pip3`) is installing packages in the right place.

**UPDATE** my setup is similar to [this one](https://medium.com/@henriquebastos/the-definitive-guide-to-setup-my-python-workspace-628d68552e14) (or, [in pt-BR](https://medium.com/welcome-to-the-django/guia-definitivo-para-organizar-meu-ambiente-python-a16e2479b753)).
