### ISSUE TITLE
Script to populate Neo4J based on Mongo

### ISSUE THREAD

**Issue by leportella** [okfn-brasil/perfil#18]

**Comment by amadeu01** [comment]
I guess instead of having to install dependencies, docker, whatever, populate db for development enviroment... 

We could make one `Makefile` for that, and scripts for each part, for instance, one script to install dependencies, other for populate data... and so on...

**Comment by cuducos** [comment]
I'm not particularly a fan of `Makefile` because it leaves Windows users out of the party.

**Comment by cuducos** [comment]
No need after #27
