### ISSUE TITLE
Add code climate.

### ISSUE THREAD

**Issue by amadeu01** [okfn-brasil/perfil#28]
@cuducos for adding codeclimate you just have to add the github app.

like:

1. Open [codeclimate.com](https://codeclimate.com/)
2. Login on it.
3. Select "Add repository"

![image](https://user-images.githubusercontent.com/11631092/43160903-de4049c6-8f5c-11e8-9217-3b64297ae106.png)

4. Add the repo you want to. 

![image](https://user-images.githubusercontent.com/11631092/43160971-12381330-8f5d-11e8-8d67-3f02e703c7c7.png)

5. Have a look at you repository on codeclimate

![image](https://user-images.githubusercontent.com/11631092/43161020-39ec628c-8f5d-11e8-9235-39cccac12ff4.png)

6. You can install codeclimate app on the github repository by going to the tab of settings 

![image](https://user-images.githubusercontent.com/11631092/43161084-68561de8-8f5d-11e8-8ccb-395a25d92f99.png)

**Comment by cuducos** [comment]
@amadeu01, this is not out priority right now. As I mentioned [elsewhere](https://github.com/okfn-brasil/perfil/pull/27#issuecomment-407518346), I can integrate the services if someone opens a PR with the tiny code changes needed for this integration.

**Comment by amadeu01** [comment]
The point is you do not really need to change any of the code bases to add it. Nevertheless, I totally understand.

**Comment by cuducos** [comment]
> The point is you do not really need to change any of the code bases to add it.

We need a file to run tests in the CI (`.travis.yml` for example) and some command in it to send the results to Code Climate, don't we?

**Comment by cuducos** [comment]
Ow… my bad. I though we're talking about going with Code Climate already with coverage. Anyway, just added the repo there.
